### ISSUE TITLE
Bot crashes when audio is detected

### ISSUE THREAD

**Issue by 0ghj04hjyg9045** [chebro/discord-voice-recorder#12]
Bot runs fine when started up until it joins a VC, it crashes and shows the following:

C1sc0 started speaking
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: ENOENT: no such file or directory, open '/home/linux/discord-voice-recorder/bin/../recordings/1612217676160.pcm'
Emitted 'error' event at:
    at errorOrDestroy (internal/streams/destroy.js:107:12)
    at WriteStream.onerror (_stream_readable.js:734:7)
    at WriteStream.emit (events.js:198:13)
    at lazyFs.open (internal/fs/streams.js:277:12)
    at FSReqWrap.args [as oncomplete] (fs.js:140:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! discord-voice-recorder@1.0.0 start: `node index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the discord-voice-recorder@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/linux/.npm/_logs/2021-02-01T22_14_36_168Z-debug.log

**Comment by chebro** [comment]
> Error: ENOENT: no such file or directory, open '/home/linux/discord-voice-recorder/bin/../recordings/1612217676160.pcm'

Did you create a recordings directory?
